export const projects = [
  {
    img: "https://tahiredits.in/wp-content/uploads/2021/06/PicsArt_06-18-12.11.37-1-257x300.jpg",
    name: "Instagram Clone",
    ext: "jsx",
    lang: "js",
    git: "https://github.com/Tizhe82/my_instagram_clone.git",
    live: "https://metaigclone.netlify.app",
  },
  {
    img: "https://camo.githubusercontent.com/f9bd57c2fdedfa1c469c5139f1972e33910a9e3ece70a9164cbccf6edfa9f331/68747470733a2f2f746865617a696d6a6f6e2e6e65746c6966792e6170702f6173736574732f696d672f706f7274666f6c696f2f706f6b656d6f6e2e706e67",
    name: "Pokemon App",
    ext: "jsx",
    lang: "js",
    git: "https://github.com/Tizhe82/my_pokemon_app",
    live: "https://pokedexx.netlify.app/",
  },
   {
      img: "https://camo.githubusercontent.com/2132be562bd65407560a12da04567f79b97fc468cb2bcb2e7383afda7f5247c1/68747470733a2f2f746865617a696d6a6f6e2e6e65746c6966792e6170702f6173736574732f696d672f706f7274666f6c696f2f63616c63756c61746f72312e706e67",
      name: "My_Calculator",
      ext: "jsx",
      lang: "js",
      git: "",
      live: "https://riactcalculator.netlify.app/",
   },
  {
    img: "https://camo.githubusercontent.com/8623c80fb44c0383deabb941ef50e01e6cd1a9a91ec5a7decaff4a989557bae7/68747470733a2f2f746865617a696d6a6f6e2e6e65746c6966792e6170702f6173736574732f696d672f706f7274666f6c696f2f79656c702e706e67",
    name: "My_Yelp",
    ext: "js",
    lang: "tsx",
    git: "https://github.com/Tizhe82/my_yelp.git",
    live: "https://d3q55hp4s1xil1.cloudfront.net"
    ,
   },
  {
    img: "https://media.licdn.com/dms/image/D4D03AQFI5gEX3vB0mA/profile-displayphoto-shrink_800_800/0/1671660037353?e=1705536000&v=beta&t=mRHVQJKtHEoDUTySVXx2-Fv8e-4bQYALOVdOUmwIwiU",
    name: "Old Portfolio",
    ext: "js",
    lang: "js",
    git: "https://github.com/Tizhe82/Portfolio",
    live: "https://tizhe82.github.io/Portfolio/",
  },

  {
    img: "https://img.lovepik.com/free_png/32/62/56/46858PICxvKKaiEk8258PIC3I_PIC2018.png_300.png",
    name: "Tetris",
    ext: "js",
    lang: "js,games",
    git: "https://github.com/Tizhe82/MyTetrisGame",
    live: "https://redhattetris.netlify.app/",
  },
  // {
  // //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/covid.png",
  // //   name: "Python Apps",
  // //   ext: "py",
  // //   lang: "py",
  // //   git: "https://github.com/smrnjeet222/Python_Apps",
  // //   live: "https://github.com/smrnjeet222/Python_Apps",
  // // },
  // // {
  // //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/surepass/bgvAll.png",
  // //   name: "Surepass",
  // //   ext: "jsx",
  // //   lang: "js",
  // //   git: "https://github.com/smrnjeet222/Surepass/blob/main/README.md",
  // //   live: "https://github.com/smrnjeet222/Surepass/blob/main/README.md",
  // // },
 
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/newslaundry.png",
  //   name: "Newslaundry",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/newslaundry",
  //   live: "https://smrnjeet222.github.io/newslaundry/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/recipe.jpg",
  //   name: "Recipe App",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/recipe-app",
  //   live: "https://smrnjeet222.github.io/recipe-app/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/bubblesort.png",
  //   name: "Visualisations",
  //   ext: "js",
  //   lang: "js",
  //   git: "https://editor.p5js.org/smrnjeet222/collections/fvtHa48dt",
  //   live: "https://editor.p5js.org/smrnjeet222/sketches/T0o5woDT5",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/dumpBox.png",
  //   name: "DumpBox",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/DropBox-Clone",
  //   live: "https://github.com/smrnjeet222/DropBox-Clone",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/pg.png",
  //   name: "Pico-Gram",
  //   ext: "jsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/PicoGram",
  //   live: "https://smrnjeet-picogram.web.app/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/BLENDER/master/Abstract_Design/Abstract.png",
  //   name: "Blender",
  //   ext: "models",
  //   lang: "games",
  //   git: "https://github.com/smrnjeet222/BLENDER",
  //   live: "https://smrnjeet222.github.io/BLENDER/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/worldRanks.png",
  //   name: "WorldRanks",
  //   ext: "tsx",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/WorldRanks",
  //   live: "https://world-ranks-smrnjeet222.vercel.app/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Unity_Gamedevelopment/master/MYGAME.png",
  //   name: "Unity Games",
  //   ext: "c#",
  //   lang: "games",
  //   git: "https://github.com/smrnjeet222/Unity_Gamedevelopment",
  //   live: "https://smrnjeet-22.itch.io/",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/background.gif",
  //   name: "NoJs-TicTacToe",
  //   ext: "css",
  //   lang: "js",
  //   git: "https://github.com/smrnjeet222/noJs-TicTacToe",
  //   live: "https://codepen.io/smrnjeet222/full/gOLjOXM",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Automail.png",
  //   name: "AutoMail",
  //   ext: "py",
  //   lang: "py",
  //   git: "https://github.com/smrnjeet222/AutoMail",
  //   live: "https://github.com/smrnjeet222/AutoMail",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Unity_Gamedevelopment/master/FreakyFrog/best.png",
  //   name: "Freaky Frog",
  //   ext: "c#",
  //   lang: "games",
  //   git: "https://github.com/smrnjeet222/Unity_Gamedevelopment",
  //   live: "https://smrnjeet-22.itch.io/freaky-frog",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Astar.png",
  //   name: "A*Pathfinding",
  //   ext: "py",
  //   lang: "py",
  //   git: "https://github.com/smrnjeet222/Python_Apps/tree/master/A-star",
  //   live: "https://repl.it/@smrnjeet222/Astar#main.py",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/Python_Apps/master/Space-invaders/Sc.jpg",
  //   name: "Space-invaders",
  //   ext: "py",
  //   lang: "py,games",
  //   git: "https://github.com/smrnjeet222/Python_Apps/tree/master/Space-invaders",
  //   live: "https://github.com/smrnjeet222/Python_Apps/tree/master/Space-invaders",
  // },
  // {
  //   img: "https://raw.githubusercontent.com/smrnjeet222/smrnjeet222/master/assets/Rc.png",
  //   name: "Ray Casting",
  //   ext: "js",
  //   lang: "js",
  //   git: "https://editor.p5js.org/smrnjeet222/collections/fvtHa48dt",
  //   live: "https://editor.p5js.org/smrnjeet222/sketches/j06TXs4ZF",
  // },
];